buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.ajoberstar.grgit:grgit-gradle:${grgitGradleVersion}"
    }
}

plugins {
    id 'groovy'
    id 'java-library'
    id "com.jfrog.artifactory" version "${artifactoryPluginVersion}" apply false
    id "org.ajoberstar.grgit" version "${grgitGradleVersion}" apply false
    id "maven-publish"
    id 'java-gradle-plugin'
}

repositories {
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'org.ajoberstar.grgit:grgit-core:5.3.2'
    implementation "org.eclipse.jgit:org.eclipse.jgit.ui:${jgitVersion}"
    implementation "org.eclipse.jgit:org.eclipse.jgit:${jgitVersion}"
    implementation 'org.tmatesoft.svnkit:svnkit:1.10.6'
    testImplementation "junit:junit:4.13.2"
    testImplementation "commons-lang:commons-lang:2.6"
    testImplementation "commons-io:commons-io:2.11.0"
}

group = 'org.labkey.build'
project.version = "1.1.4-grgit-SNAPSHOT"

gradlePlugin {
    plugins {
        versioning {
            id = "org.labkey.build"
            displayName = "Versioning plugin for Gradle"
            description = "Gradle plug-in that computes version information from the SCM"
            implementationClass = "net.nemerosa.versioning.VersioningPlugin"
        }
    }
}

publishing {
    repositories {
        if (project.version.contains("SNAPSHOT")) {
            maven {
                url = "${artifactory_contextUrl}/plugins-snapshot-local"
                credentials {
                    username = artifactory_user
                    password = artifactory_password
                }
                authentication {
                    basic(BasicAuthentication)
                    // enable preemptive authentication to get around https://www.jfrog.com/jira/browse/RTFACT-4434
                }
            }
        } else {
            maven {
                url = "${artifactory_contextUrl}/plugins-release"
                credentials {
                    username = artifactory_user
                    password = artifactory_password
                }
                authentication {
                    basic(BasicAuthentication)
                    // enable preemptive authentication to get around https://www.jfrog.com/jira/browse/RTFACT-4434
                }
            }

        }
    }
}

