# the URL for the artifact repository where our build plugins are housed
# as well as the build artifacts. (Be careful not to include a trailing slash 
# in the context URL or you will get a 500 error from artifactory.)
artifactory_contextUrl=https://labkey.jfrog.io/artifactory

sourceCompatibility=8
targetCompatibility=8

artifactoryPluginVersion=6.0.0

grgitGradleVersion=5.3.2

jgitVersion = 6.1.0.202203080745-r
